---
# Shadowsocks Download variables
# ------------------------------
shadowsocks_mirror_location: "{{ streisand_mirror_location }}/shadowsocks"
shadowsocks_mirror_href_base: "/mirror/shadowsocks"

# Android
shadowsocks_android_version: "5.2.5"
shadowsocks_android_filename: "shadowsocks-nightly-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_android_filename }}"
shadowsocks_android_url: "https://github.com/shadowsocks/shadowsocks-android/releases/download/v{{ shadowsocks_android_version }}/shadowsocks--universal-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_checksum: "sha256:77b83f22cd1cfa7d45a1da91406fff4e3a3084a4d8a2a835f6760aaecfd90cdd"

# Windows
shadowsocks_gui_version: "4.4.0"
shadowsocks_gui_build: "185"
shadowsocks_gui_filename: "Shadowsocks-{{ shadowsocks_gui_version }}.{{ shadowsocks_gui_build }}.zip"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "https://github.com/shadowsocks/shadowsocks-windows/releases/download/{{ shadowsocks_gui_version }}.0/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "sha256:a5e9856fc84492bf129cca06659842ccc9705f7e24eaa9bd6ec5d529f7c61abb"

# macOS
shadowsocks_x_ng_version: "1.9.4"
shadowsocks_x_ng_filename: "ShadowsocksX-NG.{{ shadowsocks_x_ng_version }}.zip"
shadowsocks_x_ng_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_x_ng_filename }}"
shadowsocks_x_ng_url: "https://github.com/shadowsocks/ShadowsocksX-NG/releases/download/v{{ shadowsocks_x_ng_version }}/{{ shadowsocks_x_ng_filename }}"
shadowsocks_x_ng_checksum: "sha256:dc06a995b63f8e32be9b86c265fd2979a6d73d4742d0ff16e1b2bb8f538d77a3"

# Linux (x64)
# NOTE(@cpu): if 32bit Linux clients are to be supported then we should add `shadowsocks2-linux-x86.gz`
shadowsocks_go_version: "0.1.5"
shadowsocks_go_filename: "shadowsocks2-linux.gz"
shadowsocks_go_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_go_filename }}"
shadowsocks_go_url: "https://github.com/shadowsocks/go-shadowsocks2/releases/download/v{{ shadowsocks_go_version }}/{{ shadowsocks_go_filename }}"
shadowsocks_go_checksum: "sha256:555f6a3a18b2fb3b6ca8a18f6c951d786f66da4be05bc2187ba31e245c5f2989"

shadowsocks_download_urls:
  - { url: "{{ shadowsocks_android_url }}", checksum: "{{ shadowsocks_android_checksum }}" }
  - { url: "{{ shadowsocks_gui_url }}",     checksum: "{{ shadowsocks_gui_checksum }}" }
  - { url: "{{ shadowsocks_x_ng_url }}",    checksum: "{{ shadowsocks_x_ng_checksum }}" }
  - { url: "{{ shadowsocks_go_url }}",      checksum: "{{ shadowsocks_go_checksum }}" }
