---

# Import the GPG playbook vars
- include_vars: "../../gpg/vars/main.yml"

- name: "Download the {{ project_name }} files"
  get_url:
    url: "{{ project_download_baseurl }}/{{ item.file }}"
    dest: "{{ project_download_location }}/{{ item.file }}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{ project_download_files }}"

- name: "Download the {{ project_name }} signatures"
  get_url:
    url: "{{ project_download_baseurl }}/{{ item.sig }}"
    dest: "{{ project_download_location }}/{{ item.sig }}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{ project_download_files }}"

- name: "Verify the {{ project_name }} download signatures with the Streisand GPG keyring"
  command: "gpg --verify --no-default-keyring --keyring {{ streisand_gpg_keyring }} {{ project_download_location }}/{{ item.sig }} {{ project_download_location }}/{{ item.file }}"
  environment:
    # We need to explicitly override the configured LANG, LC_MESSAGES and LC_ALL
    # env vars to ensure that we can match on English output even on systems
    # that have a non-english locale configured. It's _probably_ enough to
    # override just LANG but it sounds like there are some cases where LC_ALL
    # takes precedence and setting env vars is cheap!
    LANG: "en_US.UTF-8"
    LC_MESSAGES: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
  register: gpg_verification_results
  with_items: "{{ project_download_files }}"

- name: "Verify the {{ project_name }} download signature checks all passed"
  assert:
    that:
      - "not item.failed"
      - "item.rc == 0"
    msg: "Verifying {{ item.item.file }} GPG signature failed!!"
  with_items: "{{ gpg_verification_results.results }}"
  loop_control:
    label: "{{ item.item.file }}"
  # NOTE(@cpu): Unfortunately because of an open Ansible issue[0] related to the
  # verbosity of `assert` tasks we need a `no_log: true` here to avoid creating
  # a TON of output in the "pass" case. This `no_log` will complicate debugging
  # and should be removed if the assertions are failing.
  #
  # [0]: https://github.com/ansible/ansible/issues/27124#issuecomment-376523736
  no_log: true

- name: "Verify the {{ project_name }} download signatures were from the correct keys"
  assert:
    that:
      # By default gpg outputs to stderr. For a good signature the second line
      # always ends being like:
      # "gpg:                using RSA key 333D46306CF9D9F1F630DB8D96AEC408005D6BB4"
      # Since we've already verified the gpg return code we can just check for
      # the presence of the key ID we expect in the first line of stderr output
      # and be confident we saw a valid signature from the expected key ID and
      # not another unrelated key in the Streisand keyring.
      - "'gpg:                using RSA key {{ item.item.key }}' in '{{ item.stderr_lines[1] }}'"
    msg: "The GPG signature on {{ item.item.file }} was not from {{ item.item.key }}"
  with_items: "{{ gpg_verification_results.results }}"
  loop_control:
    label: "{{ item.item.file }}"
  # See the above `assert`'s discussion on the purpose of `no_log`.
  no_log: true
