---
- name: Ensure that BIND is not installed in order to avoid conflicts with dnsmasq
  apt:
    package: bind9
    state: absent

- name: Delete existing /etc/resolv.conf file or link
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create symlink for /etc/resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Disable systemd-resolved DNSStubListener
  lineinfile:
    path: /etc/systemd/resolved.conf
    line: DNSStubListener=no

- name: Restart system.resolved
  service:
    name: systemd-resolved
    state: restarted

- name: Install dnsmasq
  apt:
    package: dnsmasq

- name: Generate the dnsmasq configuration file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: Create the dnsmasq systemd drop-in configuration directory
  file:
    path: "{{ dnsmasq_systemd_service_path }}"
    state: directory

- name: Generate the dnsmasq systemd drop-in service file
  template:
    src: dnsmasq.service.j2
    dest: "{{ dnsmasq_systemd_service_path }}/10-restart-failure.conf"
    mode: 0644

- name: Enable the dnsmasq service
  systemd:
    daemon_reload: yes
    name: dnsmasq.service
    enabled: yes
    state: restarted
